language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .

script:
  # Run a selection of doctests and unit tests
  - pytest --doctest-modules dragonfly/parser.py
  - pytest dragonfly/test/test_parser.py
  - pytest dragonfly/test/test_engine_text.py

